name: ssurade
description: 숭실대학교 학점 조회

publish_to: 'none'

version: 0.0.2

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^5.4.3+7
  path_provider: ^2.0.11
  fluttertoast: ^8.0.9
  package_info_plus: ^1.4.2
  http: ^0.13.4
  version: ^3.0.2
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: fonts/Pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: fonts/Pretendard/Pretendard-Light.otf
          weight: 300
        - asset: fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: fonts/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: fonts/Pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: fonts/Pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: fonts/Pretendard/Pretendard-Black.otf
          weight: 900
